### ISSUE TITLE
Throw error if `$type` is a key and `=== undefined`

### ISSUE THREAD

**Issue by vkarpov15** [boosterfuels/archetype#18]
`$type: null` will still be fine, but this will help catch cases where unintentionally undefined gets through

**Comment by DyslexicDcuk** [comment]
@vkarpov15 could you show an example? I'm not sure I understand the issue.

**Comment by vkarpov15** [comment]
@DyslexicDcuk sure. Right now the below is perfectly valid:

```javascript
const Type = new Archetype({
  foo: { $type: null },
  bar: { $type: undefined }
}).compile('Type');
```

Right now the above type won't cast `foo` or `bar`. However, this can be problematic because it is easy to pass in `undefined` unintentionally:

```javascript
const mongodb = require('mongodb');

const Type = new Archetype({
  foo: { $type: null },
  bar: { $type: mongodb.OBjectId } // caps mistake intentional because this is the same as `$type: undefined`
}).compile('Type');
```

No real way to detect this class of errors. That's why I'm thinking we should disallow `$type: undefined`.

Another alternative would be to also disallow `$type: null` and instead require using a symbol like `$type: Archetype.Any` to explicitly opt in to no casting.

**Comment by DyslexicDcuk** [comment]
Thanks for the example! 

I think I like `Archetype.any` approach. It's more explicit.
