### ISSUE TITLE
new Object does not gets validated

### ISSUE THREAD

**Issue by lukaswilkeer** [boosterfuels/archetype#22]
I'm using Archetype for schema validation on a side project.
I'm using the compile option, but when I call the new constructor the object does not respect the $required rule.

Wha'ts I'm attempt to do is validate objetcts like mongoose, since archetype does not is a ODM, I can only validate the fields, plus, I'm attempted to do a password hash on a validation and gets the same message I received before.

```js
import Archetype from 'archetype'
import { passwordHash } from '../crypto.js'

const authSchema  = new Archetype({
  name: { $type: 'string', $required: true },
  last_name: { $type: 'string', $required: true },
  password: { $type: 'string', $required: true },
  email: { $type: 'string', $required: (user) => passwordHash(user.password) },
  account_type: { type: 'number', $default: () => 0, required: true },
  date_created: { type: 'date', $default: () => Date.now() }
}).compile('users')

export const authModel = authSchema
```

Also, the default options doesn't set automatically. What could I'm doing wrong? Is this way that the things occur on the archetype wordl?

Thanks in advance.

**Comment by vkarpov15** [comment]
Which fields specifically do not respect `$required`? Couple possibilities:

1) `account_type` uses `required`, not `$required`
2) I'm not sure why you're using that `passwordHash(user.password)` logic for `email`. That won't transform the `password`...

**Comment by lukaswilkeer** [comment]
Neither the email. I will fix that.

**Comment by lukaswilkeer** [comment]
up

**Comment by vkarpov15** [comment]
The below script shows that defaults get set. One issue is that you're using `$type: 'date'`, 'date' isn't a valid primitive type in JavaScript. Use `$type: Date` instead as shown below.

```javascript
const Archetype = require('archetype');

const Auth  = new Archetype({
  name: { $type: 'string', required: true },
  last_name: { $type: 'string', $required: true },
  email: { $type: 'string', $required: true },
  password: { $type: 'string', $required: (user) => 'foobar' },
  account_type: { $type: 'number', $required: true, $default: () => 0 },
  date_created: { $type: Date, $required: true, $default: () => Date.now() }
}).compile('users')

const doc = new Auth({ name: 'foo', last_name: 'bar', email: 'baz', password: 'test' });

console.log(doc);
```

**Comment by lukaswilkeer** [comment]
The password doesn't get hashed.

**Comment by vkarpov15** [comment]
That's by design. `$required` is similar to Mongoose's `required`, it determines whether or not `password` can be nullish, it doesn't actually transform the given value. You may want to try this instead:

```javascript
const Auth  = new Archetype({
  name: { $type: 'string', required: true },
  last_name: { $type: 'string', $required: true },
  email: { $type: 'string', $required: true },
  password: { $type: 'string', $required: true, $transform: v => passwordHash(v) },
  account_type: { $type: 'number', $required: true, $default: () => 0 },
  date_created: { $type: Date, $required: true, $default: () => Date.now() }
}).compile('Auth')
```
