### ISSUE TITLE
AGPL Licensed standard-error library

### ISSUE THREAD

**Issue by rcollette** [boosterfuels/archetype#23]
My organization and others such as Google will not allow use of libraries that have a transient dependencies on libraries licensed via the AGPL.

Google's Policy on AGPL
https://opensource.google/docs/using/agpl-policy/#:~:text=WARNING%3A%20Code%20licensed%20under%20the,NOT%20be%20used%20at%20Google.&text=Using%20AGPL%20software%20requires%20that,be%20licensed%20under%20the%20AGPL.

The standard-error library falls into this category.
https://github.com/moll/js-standard-error/blob/master/LICENSE

Which means we cannot use any libraries that use archetype.

Also filed an issue in the standard-error project
https://github.com/moll/js-standard-error/issues/4

**Comment by vkarpov15** [comment]
Fixed in v0.12.0, we removed standard-error as a dependency.
